# Numpy Libraries
- Processing N Dimentional array
- 

In [8]:
import numpy as np
li = [1,2,3]
a = np.array(li)
a


array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [13]:
li = [1,2,3,'z']
a = np.array(li)
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
rn=np.random.randint(0,100,size=10)
rn

array([57, 68, 50, 83, 65, 70, 54, 20, 48, 95])

In [31]:
m3 = np.random.randint(0,15,size=(3,3))
print(m3)
print(m3[0][1]) # 0th column secnd ele
print(m3[1][2])

[[ 4  8 13]
 [ 4  7 12]
 [ 1  1  7]]
8
12


In [32]:
m3 = np.random.randint(0,15,size=(3,3,3,3))
print(m3)
print(m3[2][2][2][2])

[[[[14 13  0]
   [12  9 12]
   [ 4  9 14]]

  [[ 9  7 11]
   [ 6  7  1]
   [ 8 12 13]]

  [[ 6 12  7]
   [ 7  3  8]
   [ 9 14  0]]]


 [[[ 2  3  3]
   [ 6  7  1]
   [ 0 10  9]]

  [[ 8  7 13]
   [11  4 10]
   [ 4 12 14]]

  [[11 11 13]
   [ 3  0 11]
   [ 6  3  0]]]


 [[[ 7  2  9]
   [ 6  6  2]
   [ 6  7  9]]

  [[ 7  9  2]
   [ 8  0  8]
   [ 4 13  3]]

  [[ 0  9  5]
   [ 6 11 10]
   [ 2  6  8]]]]
8


In [33]:
m3.ndim # size of m3

4

In [34]:
m3.size # how many elements

81

In [35]:
m3.shape # 

(3, 3, 3, 3)

In [36]:
m3.dtype

dtype('int32')

array([[[[14, 13,  0],
         [12,  9, 12],
         [ 4,  9, 14]],

        [[ 9,  7, 11],
         [ 6,  7,  1],
         [ 8, 12, 13]],

        [[ 6, 12,  7],
         [ 7,  3,  8],
         [ 9, 14,  0]]],


       [[[ 2,  3,  3],
         [ 6,  7,  1],
         [ 0, 10,  9]],

        [[ 8,  7, 13],
         [11,  4, 10],
         [ 4, 12, 14]],

        [[11, 11, 13],
         [ 3,  0, 11],
         [ 6,  3,  0]]],


       [[[ 7,  2,  9],
         [ 6,  6,  2],
         [ 6,  7,  9]],

        [[ 7,  9,  2],
         [ 8,  0,  8],
         [ 4, 13,  3]],

        [[ 0,  9,  5],
         [ 6, 11, 10],
         [ 2,  6,  8]]]])

In [38]:
x=[1,2,3,4,5,6,7,8,9,10]
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
x[5:]

[6, 7, 8, 9, 10]

# Pandas
- data cleaning
- data Tranformation
- Data Analysis


# Notations
+ Series
+ data frames

In [42]:
import pandas as pd
internal1 = {'s1':21,'s2': 18,'s3' : 24}
internal1= pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [43]:
import pandas as pd
internal2 = {'s1':24,'s2': 15,'s3' : 20}
internal2= pd.Series(internal2)
internal2

s1    24
s2    15
s3    20
dtype: int64

In [46]:
final={'internal1':internal1,'internal2': internal2}
final=pd.DataFrame(final)
final

internal1  internal2
s1         21         24
s2         18         15
s3         24         20

In [47]:
final.columns

Index(['internal1', 'internal2'], dtype='object')

In [48]:
final.values

array([[21, 24],
       [18, 15],
       [24, 20]], dtype=int64)

In [49]:
print(final.values[2,0])
print(final.values[2][1])

24
20


In [51]:
for row in final.values:
    print('internal-',row[0],'internal',row[1])

internal- 21 internal 24
internal- 18 internal 15
internal- 24 internal 20


In [53]:
final.loc[3]=[15,18]
final

internal1  internal2
s1         21         24
s2         18         15
s3         24         20
3          15         18

In [60]:
final1 = final.drop('s1')
final1

internal1  internal2
s2         18         15
s3         12         25
3          15         18

In [65]:
final.values[1] = [12,25]
final1

internal1  internal2
s2         18         15
s3         12         25
3          15         18

# Reading CSV file data

In [67]:
# 
import pandas as pd
filepath = 'Datafiles/Income.csv'
incomedf=pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [76]:
for row in incomedf.values:
    print(row[1]+':',row[-9])

Alabama: 37150
Alaska: 55891
Arizona: 45245
Arkansas: 36658
California: 51755


In [68]:
# avg income of arizona
sum=0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [ ]:
# Avg